### ISSUE TITLE
example report on docs site returning a 404

### ISSUE THREAD

**Issue by Analect** [ropensci/daiquiri#6]
Thanks for your package.  Just wanted to bring this to your attention.

![image](https://user-images.githubusercontent.com/4063815/203293808-0ba66232-be70-4f6e-a1b9-23be458063e3.png)

**Comment by phuongquan** [comment]
Thanks for letting me know.  Please use the docs site at [https://ropensci.github.io/daiquiri/](https://ropensci.github.io/daiquiri/) (where the example report is working) until I can figure out how to get the rOpenSci docs builder to do what I want it to.

**Comment by Analect** [comment]
@phuongquan ... just a quick follow-on question. I was trying to render the `daiquiri_report()` from within an IDE.  I couldn't get it working in a *.qmd (quarto) file on vscode.  I was also having difficulty rendering it from a jupyter notebook running an r kernel.  Is it intended that it only renders easily within an rstudio environment?
